"""adding uuid

Revision ID: cdfa2f6242a7
Revises: 78d6ac4dca16
Create Date: 2020-03-14 22:06:25.691123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdfa2f6242a7'
down_revision = '78d6ac4dca16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.create_unique_constraint(op.f('uq_messages_uuid'), 'messages', ['uuid'])
    op.add_column('rooms', sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.create_unique_constraint(op.f('uq_rooms_uuid'), 'rooms', ['uuid'])
    op.add_column('users', sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.create_unique_constraint(op.f('uq_users_uuid'), 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_uuid'), 'users', type_='unique')
    op.drop_column('users', 'uuid')
    op.drop_constraint(op.f('uq_rooms_uuid'), 'rooms', type_='unique')
    op.drop_column('rooms', 'uuid')
    op.drop_constraint(op.f('uq_messages_uuid'), 'messages', type_='unique')
    op.drop_column('messages', 'uuid')
    # ### end Alembic commands ###